name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  Docker-Push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login
      run: |
        docker login -u ugorwx \
        -p ${{ secrets.DOCKER_TOKEN }}

    - name: Build
      run: docker build . -t ugorwx/fsub

    - name: Push
      run: docker push ugorwx/fsub
